POST  http://laumeet.vercel.app/api/auth/signup
Content-Type: application/json

{
    "username": "Emmanuel",
    "password": "helloE@123",
    "security_question": "Who is your mother",
    "security_answer":"Hello",
    "age":"47",
    "gender":"male"
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "Emmanueli",
    "password": "helloE@123",
    "security_question": "Who is your mother",
    "security_answer":"Hello",
    "age":"47",
    "gender":"male"
}
###
GET https://laumeet.onrender.com/debug/auth
###
GET  http://127.0.0.1:5000/profile
Cookie: access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1OTQ5MDgwOSwianRpIjoiZWYyOTE3NjUtZjNiYS00ODkyLTllMTItMmQyYmQyNGZmYmMzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3NTk0OTA4MDksImV4cCI6MTc1OTU3NzIwOX0.5aGAiAegmJI9wTtIrxL_TDhFw7AYgObZ1JpYKtNUtbU
###
POST  http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "hello",
    "password": "helloE@123"
}