POST  http://laumeet.vercel.app/api/auth/signup
Content-Type: application/json

{
    "username": "Emmanuel",
    "password": "helloE@123",
    "security_question": "Who is your mother",
    "security_answer":"Hello",
    "age":"47",
    "gender":"female"
}
###
POST  http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "Emmanuel",
    "password": "helloE@123",
    "security_question": "Who is your mother",
    "security_answer":"Hello",
    "age":"47",
    "gender":"male"
}
###
GET https://laumeet.onrender.com/debug/auth
###
GET  http://127.0.0.1:5000/profile
Cookie: access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1OTg0NTQ2OSwianRpIjoiNDgzNzU1MTMtZGRiMS00NzBlLTkwMTktYjlmYWFjYzkzOGI2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjJiNGI5NWYxLWZlYjQtNGMzZC05OTAzLWI1ZWFhODAzMGFjMiIsIm5iZiI6MTc1OTg0NTQ2OSwiZXhwIjoxNzU5OTMxODY5fQ.mmVw2t0PKxYXY6ZLjCEsl-9ISZ_zKJfS3hz-SrMicyE
###
GET  http://127.0.0.1:5000//health
Cookie: access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1OTg0NTQ2OSwianRpIjoiNDgzNzU1MTMtZGRiMS00NzBlLTkwMTktYjlmYWFjYzkzOGI2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjJiNGI5NWYxLWZlYjQtNGMzZC05OTAzLWI1ZWFhODAzMGFjMiIsIm5iZiI6MTc1OTg0NTQ2OSwiZXhwIjoxNzU5OTMxODY5fQ.mmVw2t0PKxYXY6ZLjCEsl-9ISZ_zKJfS3hz-SrMicyE
# Content-Type: application/json

# {
#     "username": "hello",
#     "password": "helloE@123"
# }